title: Raofu
description: Raofu identifies users on Reddit responsible for brigading.
creator:
  name: Kit Maywood
  url: http://twitter.com/kittsville
  twitter: kittsville
navigation:
  - title: App
    url: /a/
  - title: About
    url: /about/
  - title: News
    url: https://reddit.com/r/Raofu
  - title: FAQ
    url: /faq/
  - title: Terms of Service
    url: /terms/
  - title: Privacy
    url: /privacy/
app_navigation:
  - title: Results
    url: /a/results/
  - title: New
    url: /a/results/new/
  - title: Terms of Service
    url: /terms/
  - title: Privacy
    url: /privacy/
rendant_api: http://api.raofu.localhost/v1
exclude: ['LICENSE', 'README.md']
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-assets
  - uglifier
assets:
  features:
    liquid: true
  sources:
    - _assets/scripts
    - _assets/styles
  js_compressor:  uglifier
  css_compressor: sass
sass:
  style: compressed
webrick:
  headers:
    X-Clacks-Overhead: GNU Terry Pratchett
