title: Raofu
description: Raofu identifies users on Reddit responsible for brigading.
creator:
  name: Kit Maywood
  url: http://twitter.com/kittsville
  twitter: kittsville
navigation:
  - title: About
    url: /about/
  - title: News
    url: https://reddit.com/r/Raofu
  - title: FAQ
    url: /faq/
  - title: Terms of Service
    url: /terms/
  - title: Privacy
    url: /privacy/
exclude: ['LICENSE', 'README.md']
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
sass:
  style: compressed
webrick:
  headers:
    X-Clacks-Overhead: GNU Terry Pratchett
